# Generated by Django 5.1.3 on 2024-11-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='item_type',
            field=models.CharField(default='osef', max_length=100),
            preserve_default=False,
        ),
    ]
